/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.editor_overlay[_ngcontent-%COMP%]{\r\n    background: rgba(11,122,167,0.6);\r\n    position: absolute;\r\n    top: 0;\r\n    left: 0;\r\n    right: 0;\r\n    bottom: 0;\r\n    display: flex;\r\n    align-items: center;\r\n    justify-content: center;\r\n    z-index: 2;\r\n}\r\n\r\n.editor_overlay[_ngcontent-%COMP%]   .button[_ngcontent-%COMP%]{\r\n    padding: 5px 10px;\r\n}'];