/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './pagenotfound.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
var renderType_PageNotFoundComponent_Host:import0.RenderComponentType = (null as any);
class _View_PageNotFoundComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _PageNotFoundComponent_0_4:import3.PageNotFoundComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PageNotFoundComponent_Host0,renderType_PageNotFoundComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('dip-404',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PageNotFoundComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PageNotFoundComponent_0_4 = new import3.PageNotFoundComponent();
    this._appEl_0.initComponent(this._PageNotFoundComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._PageNotFoundComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.PageNotFoundComponent) && (0 === requestNodeIndex))) { return this._PageNotFoundComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_PageNotFoundComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_PageNotFoundComponent_Host === (null as any))) { (renderType_PageNotFoundComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_PageNotFoundComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const PageNotFoundComponentNgFactory:import9.ComponentFactory<import3.PageNotFoundComponent> = new import9.ComponentFactory<import3.PageNotFoundComponent>('dip-404',viewFactory_PageNotFoundComponent_Host0,import3.PageNotFoundComponent);
const styles_PageNotFoundComponent:any[] = ([] as any[]);
var renderType_PageNotFoundComponent:import0.RenderComponentType = (null as any);
class _View_PageNotFoundComponent0 extends import1.AppView<import3.PageNotFoundComponent> {
  _text_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PageNotFoundComponent0,renderType_PageNotFoundComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'error',(null as any));
    this.init(([] as any[]),[this._text_0],([] as any[]),([] as any[]));
    return (null as any);
  }
}
export function viewFactory_PageNotFoundComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.PageNotFoundComponent> {
  if ((renderType_PageNotFoundComponent === (null as any))) { (renderType_PageNotFoundComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_PageNotFoundComponent,{})); }
  return new _View_PageNotFoundComponent0(viewUtils,parentInjector,declarationEl);
}