/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './main-layout-rows.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/common/src/directives/ng_for';
import * as import11 from '../../pipes/sanitize-html.pipe';
import * as import12 from '@angular/core/src/linker/template_ref';
import * as import13 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import14 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import15 from '@angular/common/src/directives/ng_class';
import * as import16 from '@angular/common/src/directives/ng_style';
import * as import17 from '@angular/common/src/directives/ng_if';
import * as import18 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@angular/core/src/security';
var renderType_MainLayoutRowsComponent_Host:import0.RenderComponentType = (null as any);
class _View_MainLayoutRowsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _MainLayoutRowsComponent_0_4:import3.MainLayoutRowsComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MainLayoutRowsComponent_Host0,renderType_MainLayoutRowsComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('dip-main-layout-rows',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MainLayoutRowsComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MainLayoutRowsComponent_0_4 = new import3.MainLayoutRowsComponent();
    this._appEl_0.initComponent(this._MainLayoutRowsComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._MainLayoutRowsComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.MainLayoutRowsComponent) && (0 === requestNodeIndex))) { return this._MainLayoutRowsComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._MainLayoutRowsComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MainLayoutRowsComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_MainLayoutRowsComponent_Host === (null as any))) { (renderType_MainLayoutRowsComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_MainLayoutRowsComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const MainLayoutRowsComponentNgFactory:import9.ComponentFactory<import3.MainLayoutRowsComponent> = new import9.ComponentFactory<import3.MainLayoutRowsComponent>('dip-main-layout-rows',viewFactory_MainLayoutRowsComponent_Host0,import3.MainLayoutRowsComponent);
const styles_MainLayoutRowsComponent:any[] = ([] as any[]);
var renderType_MainLayoutRowsComponent:import0.RenderComponentType = (null as any);
class _View_MainLayoutRowsComponent0 extends import1.AppView<import3.MainLayoutRowsComponent> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import10.NgFor;
  _text_3:any;
  /*private*/ _expr_0:any;
  _pipe_sanitizeHtml_0:import11.SanitizeHtml;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MainLayoutRowsComponent0,renderType_MainLayoutRowsComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import12.TemplateRef_(this._appEl_2,viewFactory_MainLayoutRowsComponent1);
    this._NgFor_2_6 = new import10.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parentInjector.get(import13.IterableDiffers),this.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._pipe_sanitizeHtml_0 = new import11.SanitizeHtml(this.parentInjector.get(import14.DomSanitizer));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import10.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.context.main.items;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_2_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_MainLayoutRowsComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.MainLayoutRowsComponent> {
  if ((renderType_MainLayoutRowsComponent === (null as any))) { (renderType_MainLayoutRowsComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_MainLayoutRowsComponent,{})); }
  return new _View_MainLayoutRowsComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_MainLayoutRowsComponent1 extends import1.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import15.NgClass;
  _NgStyle_0_4:import16.NgStyle;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import17.NgIf;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _NgStyle_6_3:import16.NgStyle;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _map_0:any;
  /*private*/ _expr_0:any;
  _map_1:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  _map_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  _pipe_sanitizeHtml_0_0:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MainLayoutRowsComponent1,renderType_MainLayoutRowsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'style','display: flex;');
    this._NgClass_0_3 = new import15.NgClass(this.parent.parentInjector.get(import13.IterableDiffers),this.parent.parentInjector.get(import18.KeyValueDiffers),new import19.ElementRef(this._el_0),this.renderer);
    this._NgStyle_0_4 = new import16.NgStyle(this.parent.parentInjector.get(import18.KeyValueDiffers),new import19.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import12.TemplateRef_(this._appEl_2,viewFactory_MainLayoutRowsComponent2);
    this._NgIf_2_6 = new import17.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','align-center');
    this.renderer.setElementAttribute(this._el_4,'style','padding: 20px; box-sizing: border-box; width: 60%;');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h1',(null as any));
    this._NgStyle_6_3 = new import16.NgStyle(this.parent.parentInjector.get(import18.KeyValueDiffers),new import19.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','break-word top10');
    this._text_10 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {'reverse-row': p0};
    });
    this._expr_0 = import7.UNINITIALIZED;
    this._map_1 = import4.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        paddingTop: p0,
        paddingBottom: p1
      }
      ;
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._map_2 = import4.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        color: p0,
        'font-size': p1
      }
      ;
    });
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._pipe_sanitizeHtml_0_0 = import4.pureProxy1((<_View_MainLayoutRowsComponent0>this.parent)._pipe_sanitizeHtml_0.transform.bind((<_View_MainLayoutRowsComponent0>this.parent)._pipe_sanitizeHtml_0));
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import17.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import16.NgStyle) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._NgStyle_6_3; }
    if (((token === import15.NgClass) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgClass_0_3; }
    if (((token === import16.NgStyle) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgStyle_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_0:any = this._map_0(((this.context.index % 2) != 0));
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgClass_0_3.ngClass = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (!throwOnChange) { this._NgClass_0_3.ngDoCheck(); }
    const currVal_1:any = this._map_1(this.parent.context.main.padding_items,this.parent.context.main.padding_items);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgStyle_0_4.ngStyle = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (!throwOnChange) { this._NgStyle_0_4.ngDoCheck(); }
    const currVal_2:any = this.context.$implicit.image;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_2_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._map_2(this.parent.context.main.title_color,this.parent.context.main.title_size);
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgStyle_6_3.ngStyle = currVal_3;
      this._expr_3 = currVal_3;
    }
    if (!throwOnChange) { this._NgStyle_6_3.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = import4.interpolate(1,'\n                ',this.context.$implicit.title,'\n            ');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_7,currVal_4);
      this._expr_4 = currVal_4;
    }
    valUnwrapper.reset();
    const currVal_5:any = valUnwrapper.unwrap(import4.castByValue(this._pipe_sanitizeHtml_0_0,(<_View_MainLayoutRowsComponent0>this.parent)._pipe_sanitizeHtml_0.transform)(this.context.$implicit.description));
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_5,currVal_5))) {
      this.renderer.setElementProperty(this._el_9,'innerHTML',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.HTML,currVal_5));
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MainLayoutRowsComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MainLayoutRowsComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_MainLayoutRowsComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MainLayoutRowsComponent2,renderType_MainLayoutRowsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'style','width: 40%;');
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'img',(null as any));
    this.renderer.setElementAttribute(this._el_2,'style','width: 100%;');
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'/uploaded/',this.parent.context.$implicit.image.filename,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MainLayoutRowsComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MainLayoutRowsComponent2(viewUtils,parentInjector,declarationEl);
}