/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.account-box[_ngcontent-%COMP%] {\r\n    position: relative;\r\n    width: 200px;\r\n    max-width: 200px;\r\n    text-align: center;\r\n}\r\n.account-box[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]{\r\n    position: absolute;\r\n    top: 100%;\r\n    right: 0;\r\n    left: 0;\r\n    max-width: 200px;\r\n    background: white;\r\n}\r\n.account-box[_ngcontent-%COMP%]   li[_ngcontent-%COMP%] {\r\n    padding: 10px 20px;\r\n    border-bottom: 1px solid gray;\r\n    cursor: pointer;\r\n    width: 100%;\r\n    box-sizing: border-box;\r\n}\r\n.account-box[_ngcontent-%COMP%]   .username[_ngcontent-%COMP%]{\r\n    text-overflow: ellipsis;\r\n    overflow: hidden;\r\n}'];