/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './auth.module';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '@angular/forms/src/directives';
import * as import4 from '@angular/forms/src/form_providers';
import * as import5 from '@angular/common/src/common_module';
import * as import6 from 'ng2-uploader/src/module/ng2-uploader.module';
import * as import7 from '../shared/shared.module';
import * as import8 from '@angular/forms/src/form_builder';
import * as import9 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import10 from '@angular/common/src/localization';
import * as import11 from 'ng2-uploader/src/services/ng2-uploader';
import * as import12 from '@angular/core/src/di/injector';
import * as import13 from './auth.component.ngfactory';
import * as import14 from './login.component.ngfactory';
import * as import15 from './signup.component.ngfactory';
import * as import16 from '@angular/core/src/i18n/tokens';
import * as import17 from './auth.component';
import * as import18 from './login.component';
import * as import19 from './signup.component';
import * as import20 from '@angular/router/src/router_config_loader';
class AuthModuleInjector extends import0.NgModuleInjector<import1.AuthModule> {
  _RouterModule_0:import2.RouterModule;
  _InternalFormsSharedModule_1:import3.InternalFormsSharedModule;
  _ReactiveFormsModule_2:import4.ReactiveFormsModule;
  _CommonModule_3:import5.CommonModule;
  _FormsModule_4:import4.FormsModule;
  _Ng2UploaderModule_5:import6.Ng2UploaderModule;
  _SharedModule_6:import7.SharedModule;
  _AuthModule_7:import1.AuthModule;
  __FormBuilder_8:import8.FormBuilder;
  __RadioControlRegistry_9:import9.RadioControlRegistry;
  __NgLocalization_10:import10.NgLocaleLocalization;
  __Ng2Uploader_11:import11.Ng2Uploader;
  __ROUTES_12:any[];
  constructor(parent:import12.Injector) {
    super(parent,[
      import13.AuthComponentNgFactory,
      import14.LoginComponentNgFactory,
      import15.SignupComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _FormBuilder_8():import8.FormBuilder {
    if ((this.__FormBuilder_8 == (null as any))) { (this.__FormBuilder_8 = new import8.FormBuilder()); }
    return this.__FormBuilder_8;
  }
  get _RadioControlRegistry_9():import9.RadioControlRegistry {
    if ((this.__RadioControlRegistry_9 == (null as any))) { (this.__RadioControlRegistry_9 = new import9.RadioControlRegistry()); }
    return this.__RadioControlRegistry_9;
  }
  get _NgLocalization_10():import10.NgLocaleLocalization {
    if ((this.__NgLocalization_10 == (null as any))) { (this.__NgLocalization_10 = new import10.NgLocaleLocalization(this.parent.get(import16.LOCALE_ID))); }
    return this.__NgLocalization_10;
  }
  get _Ng2Uploader_11():import11.Ng2Uploader {
    if ((this.__Ng2Uploader_11 == (null as any))) { (this.__Ng2Uploader_11 = new import11.Ng2Uploader()); }
    return this.__Ng2Uploader_11;
  }
  get _ROUTES_12():any[] {
        if ((this.__ROUTES_12 == (null as any))) { (this.__ROUTES_12 = [[{
          path: '',
          component: import17.AuthComponent,
          children: [
            {
              path: 'login',
              component: import18.LoginComponent
            }
            ,
            {
              path: 'signup',
              component: import19.SignupComponent
            }

          ]

        }
    ]]); }
    return this.__ROUTES_12;
  }
  createInternal():import1.AuthModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ROUTER_FORROOT_GUARD,(null as any)));
    this._InternalFormsSharedModule_1 = new import3.InternalFormsSharedModule();
    this._ReactiveFormsModule_2 = new import4.ReactiveFormsModule();
    this._CommonModule_3 = new import5.CommonModule();
    this._FormsModule_4 = new import4.FormsModule();
    this._Ng2UploaderModule_5 = new import6.Ng2UploaderModule();
    this._SharedModule_6 = new import7.SharedModule();
    this._AuthModule_7 = new import1.AuthModule();
    return this._AuthModule_7;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import3.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_1; }
    if ((token === import4.ReactiveFormsModule)) { return this._ReactiveFormsModule_2; }
    if ((token === import5.CommonModule)) { return this._CommonModule_3; }
    if ((token === import4.FormsModule)) { return this._FormsModule_4; }
    if ((token === import6.Ng2UploaderModule)) { return this._Ng2UploaderModule_5; }
    if ((token === import7.SharedModule)) { return this._SharedModule_6; }
    if ((token === import1.AuthModule)) { return this._AuthModule_7; }
    if ((token === import8.FormBuilder)) { return this._FormBuilder_8; }
    if ((token === import9.RadioControlRegistry)) { return this._RadioControlRegistry_9; }
    if ((token === import10.NgLocalization)) { return this._NgLocalization_10; }
    if ((token === import11.Ng2Uploader)) { return this._Ng2Uploader_11; }
    if ((token === import20.ROUTES)) { return this._ROUTES_12; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AuthModuleNgFactory:import0.NgModuleFactory<import1.AuthModule> = new import0.NgModuleFactory(AuthModuleInjector,import1.AuthModule);