/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './signup.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/forms/src/form_builder';
import * as import9 from './auth.service';
import * as import10 from '../error/error.service';
import * as import11 from '@angular/router/src/router';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '../error/error.component';
import * as import15 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import16 from '@angular/forms/src/directives/ng_control_status';
import * as import17 from '@angular/forms/src/directives/default_value_accessor';
import * as import18 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import19 from '../error/error.component.ngfactory';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/forms/src/directives/control_value_accessor';
import * as import22 from '@angular/forms/src/directives/ng_control';
import * as import23 from '@angular/forms/src/directives/control_container';
var renderType_SignupComponent_Host:import0.RenderComponentType = (null as any);
class _View_SignupComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SignupComponent_0_4:import3.SignupComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignupComponent_Host0,renderType_SignupComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('dip-signup',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SignupComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SignupComponent_0_4 = new import3.SignupComponent(this.parentInjector.get(import8.FormBuilder),this.parentInjector.get(import9.AuthService),this.parentInjector.get(import10.ErrorService),this.parentInjector.get(import11.Router));
    this._appEl_0.initComponent(this._SignupComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._SignupComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SignupComponent) && (0 === requestNodeIndex))) { return this._SignupComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SignupComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignupComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SignupComponent_Host === (null as any))) { (renderType_SignupComponent_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SignupComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SignupComponentNgFactory:import13.ComponentFactory<import3.SignupComponent> = new import13.ComponentFactory<import3.SignupComponent>('dip-signup',viewFactory_SignupComponent_Host0,import3.SignupComponent);
const styles_SignupComponent:any[] = ([] as any[]);
var renderType_SignupComponent:import0.RenderComponentType = (null as any);
class _View_SignupComponent0 extends import1.AppView<import3.SignupComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _ErrorComponent_5_4:import14.ErrorComponent;
  _text_6:any;
  _el_7:any;
  _FormGroupDirective_7_3:import15.FormGroupDirective;
  _ControlContainer_7_4:any;
  _NgControlStatusGroup_7_5:import16.NgControlStatusGroup;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _DefaultValueAccessor_11_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_11_4:any[];
  _FormControlName_11_5:import18.FormControlName;
  _NgControl_11_6:any;
  _NgControlStatus_11_7:import16.NgControlStatus;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _DefaultValueAccessor_19_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_19_4:any[];
  _FormControlName_19_5:import18.FormControlName;
  _NgControl_19_6:any;
  _NgControlStatus_19_7:import16.NgControlStatus;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _DefaultValueAccessor_27_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_27_4:any[];
  _FormControlName_27_5:import18.FormControlName;
  _NgControl_27_6:any;
  _NgControlStatus_27_7:import16.NgControlStatus;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _DefaultValueAccessor_35_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_35_4:any[];
  _FormControlName_35_5:import18.FormControlName;
  _NgControl_35_6:any;
  _NgControlStatus_35_7:import16.NgControlStatus;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _DefaultValueAccessor_43_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_43_4:any[];
  _FormControlName_43_5:import18.FormControlName;
  _NgControl_43_6:any;
  _NgControlStatus_43_7:import16.NgControlStatus;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_55:any;
  /*private*/ _expr_56:any;
  /*private*/ _expr_57:any;
  /*private*/ _expr_58:any;
  /*private*/ _expr_59:any;
  /*private*/ _expr_60:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignupComponent0,renderType_SignupComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','card centered');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','card-title');
    this._text_3 = this.renderer.createText(this._el_2,'Sign up',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'dip-error',(null as any));
    this._appEl_5 = new import2.AppElement(5,0,this,this._el_5);
    var compView_5:any = import19.viewFactory_ErrorComponent0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ErrorComponent_5_4 = new import14.ErrorComponent(this.parentInjector.get(import10.ErrorService));
    this._appEl_5.initComponent(this._ErrorComponent_5_4,([] as any[]),compView_5);
    compView_5.create(this._ErrorComponent_5_4,([] as any[]),(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_0,'form',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','top10');
    this._FormGroupDirective_7_3 = new import15.FormGroupDirective((null as any),(null as any));
    this._ControlContainer_7_4 = this._FormGroupDirective_7_3;
    this._NgControlStatusGroup_7_5 = new import16.NgControlStatusGroup(this._ControlContainer_7_4);
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','input-field');
    this._text_10 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'input',(null as any));
    this.renderer.setElementAttribute(this._el_11,'formControlName','firstName');
    this.renderer.setElementAttribute(this._el_11,'id','firstName');
    this.renderer.setElementAttribute(this._el_11,'name','firstName');
    this.renderer.setElementAttribute(this._el_11,'type','text');
    this._DefaultValueAccessor_11_3 = new import17.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_11));
    this._NG_VALUE_ACCESSOR_11_4 = [this._DefaultValueAccessor_11_3];
    this._FormControlName_11_5 = new import18.FormControlName(this._ControlContainer_7_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_11_4);
    this._NgControl_11_6 = this._FormControlName_11_5;
    this._NgControlStatus_11_7 = new import16.NgControlStatus(this._NgControl_11_6);
    this._text_12 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_9,'label',(null as any));
    this.renderer.setElementAttribute(this._el_13,'for','firstName');
    this._text_14 = this.renderer.createText(this._el_13,'First name',(null as any));
    this._text_15 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._text_16 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','input-field');
    this._text_18 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'input',(null as any));
    this.renderer.setElementAttribute(this._el_19,'formControlName','lastName');
    this.renderer.setElementAttribute(this._el_19,'id','lastName');
    this.renderer.setElementAttribute(this._el_19,'name','lastName');
    this.renderer.setElementAttribute(this._el_19,'type','text');
    this._DefaultValueAccessor_19_3 = new import17.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_19));
    this._NG_VALUE_ACCESSOR_19_4 = [this._DefaultValueAccessor_19_3];
    this._FormControlName_19_5 = new import18.FormControlName(this._ControlContainer_7_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_19_4);
    this._NgControl_19_6 = this._FormControlName_19_5;
    this._NgControlStatus_19_7 = new import16.NgControlStatus(this._NgControl_19_6);
    this._text_20 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_17,'label',(null as any));
    this.renderer.setElementAttribute(this._el_21,'for','lastName');
    this._text_22 = this.renderer.createText(this._el_21,'Last name',(null as any));
    this._text_23 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','input-field');
    this._text_26 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'input',(null as any));
    this.renderer.setElementAttribute(this._el_27,'formControlName','email');
    this.renderer.setElementAttribute(this._el_27,'id','email');
    this.renderer.setElementAttribute(this._el_27,'name','email');
    this.renderer.setElementAttribute(this._el_27,'type','email');
    this._DefaultValueAccessor_27_3 = new import17.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_27));
    this._NG_VALUE_ACCESSOR_27_4 = [this._DefaultValueAccessor_27_3];
    this._FormControlName_27_5 = new import18.FormControlName(this._ControlContainer_7_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_27_4);
    this._NgControl_27_6 = this._FormControlName_27_5;
    this._NgControlStatus_27_7 = new import16.NgControlStatus(this._NgControl_27_6);
    this._text_28 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_25,'label',(null as any));
    this.renderer.setElementAttribute(this._el_29,'for','email');
    this._text_30 = this.renderer.createText(this._el_29,'Email',(null as any));
    this._text_31 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','input-field');
    this._text_34 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'input',(null as any));
    this.renderer.setElementAttribute(this._el_35,'formControlName','password');
    this.renderer.setElementAttribute(this._el_35,'id','password');
    this.renderer.setElementAttribute(this._el_35,'name','password');
    this.renderer.setElementAttribute(this._el_35,'type','password');
    this._DefaultValueAccessor_35_3 = new import17.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_35));
    this._NG_VALUE_ACCESSOR_35_4 = [this._DefaultValueAccessor_35_3];
    this._FormControlName_35_5 = new import18.FormControlName(this._ControlContainer_7_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_35_4);
    this._NgControl_35_6 = this._FormControlName_35_5;
    this._NgControlStatus_35_7 = new import16.NgControlStatus(this._NgControl_35_6);
    this._text_36 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_33,'label',(null as any));
    this.renderer.setElementAttribute(this._el_37,'for','password');
    this._text_38 = this.renderer.createText(this._el_37,'Password',(null as any));
    this._text_39 = this.renderer.createText(this._el_33,'\n        ',(null as any));
    this._text_40 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','input-field');
    this._text_42 = this.renderer.createText(this._el_41,'\n            ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_41,'input',(null as any));
    this.renderer.setElementAttribute(this._el_43,'formControlName','confirmPassword');
    this.renderer.setElementAttribute(this._el_43,'id','confirmPassword');
    this.renderer.setElementAttribute(this._el_43,'name','confirmPassword');
    this.renderer.setElementAttribute(this._el_43,'type','password');
    this._DefaultValueAccessor_43_3 = new import17.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_43));
    this._NG_VALUE_ACCESSOR_43_4 = [this._DefaultValueAccessor_43_3];
    this._FormControlName_43_5 = new import18.FormControlName(this._ControlContainer_7_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_43_4);
    this._NgControl_43_6 = this._FormControlName_43_5;
    this._NgControlStatus_43_7 = new import16.NgControlStatus(this._NgControl_43_6);
    this._text_44 = this.renderer.createText(this._el_41,'\n            ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_41,'label',(null as any));
    this.renderer.setElementAttribute(this._el_45,'for','confirmPassword');
    this._text_46 = this.renderer.createText(this._el_45,'Confirm password',(null as any));
    this._text_47 = this.renderer.createText(this._el_41,'\n        ',(null as any));
    this._text_48 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_49,'class','button top20');
    this.renderer.setElementAttribute(this._el_49,'type','submit');
    this._text_50 = this.renderer.createText(this._el_49,'\n            Sign up\n        ',(null as any));
    this._text_51 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_52 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_7,'ngSubmit',this.eventHandler(this._handle_ngSubmit_7_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_7,'submit',this.eventHandler(this._handle_submit_7_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_7,'reset',this.eventHandler(this._handle_reset_7_2.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._FormGroupDirective_7_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_7_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_11,'input',this.eventHandler(this._handle_input_11_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_11,'blur',this.eventHandler(this._handle_blur_11_1.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_19,'input',this.eventHandler(this._handle_input_19_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_19,'blur',this.eventHandler(this._handle_blur_19_1.bind(this)));
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_27,'input',this.eventHandler(this._handle_input_27_0.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_27,'blur',this.eventHandler(this._handle_blur_27_1.bind(this)));
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_35,'input',this.eventHandler(this._handle_input_35_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_35,'blur',this.eventHandler(this._handle_blur_35_1.bind(this)));
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    var disposable_11:Function = this.renderer.listen(this._el_43,'input',this.eventHandler(this._handle_input_43_0.bind(this)));
    var disposable_12:Function = this.renderer.listen(this._el_43,'blur',this.eventHandler(this._handle_blur_43_1.bind(this)));
    this._expr_53 = import7.UNINITIALIZED;
    this._expr_54 = import7.UNINITIALIZED;
    this._expr_55 = import7.UNINITIALIZED;
    this._expr_56 = import7.UNINITIALIZED;
    this._expr_57 = import7.UNINITIALIZED;
    this._expr_58 = import7.UNINITIALIZED;
    this._expr_59 = import7.UNINITIALIZED;
    this._expr_60 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._text_52
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.ErrorComponent) && (5 === requestNodeIndex))) { return this._ErrorComponent_5_4; }
    if (((token === import17.DefaultValueAccessor) && (11 === requestNodeIndex))) { return this._DefaultValueAccessor_11_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (11 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_11_4; }
    if (((token === import18.FormControlName) && (11 === requestNodeIndex))) { return this._FormControlName_11_5; }
    if (((token === import22.NgControl) && (11 === requestNodeIndex))) { return this._NgControl_11_6; }
    if (((token === import16.NgControlStatus) && (11 === requestNodeIndex))) { return this._NgControlStatus_11_7; }
    if (((token === import17.DefaultValueAccessor) && (19 === requestNodeIndex))) { return this._DefaultValueAccessor_19_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (19 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_19_4; }
    if (((token === import18.FormControlName) && (19 === requestNodeIndex))) { return this._FormControlName_19_5; }
    if (((token === import22.NgControl) && (19 === requestNodeIndex))) { return this._NgControl_19_6; }
    if (((token === import16.NgControlStatus) && (19 === requestNodeIndex))) { return this._NgControlStatus_19_7; }
    if (((token === import17.DefaultValueAccessor) && (27 === requestNodeIndex))) { return this._DefaultValueAccessor_27_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (27 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_27_4; }
    if (((token === import18.FormControlName) && (27 === requestNodeIndex))) { return this._FormControlName_27_5; }
    if (((token === import22.NgControl) && (27 === requestNodeIndex))) { return this._NgControl_27_6; }
    if (((token === import16.NgControlStatus) && (27 === requestNodeIndex))) { return this._NgControlStatus_27_7; }
    if (((token === import17.DefaultValueAccessor) && (35 === requestNodeIndex))) { return this._DefaultValueAccessor_35_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (35 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_35_4; }
    if (((token === import18.FormControlName) && (35 === requestNodeIndex))) { return this._FormControlName_35_5; }
    if (((token === import22.NgControl) && (35 === requestNodeIndex))) { return this._NgControl_35_6; }
    if (((token === import16.NgControlStatus) && (35 === requestNodeIndex))) { return this._NgControlStatus_35_7; }
    if (((token === import17.DefaultValueAccessor) && (43 === requestNodeIndex))) { return this._DefaultValueAccessor_43_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (43 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_43_4; }
    if (((token === import18.FormControlName) && (43 === requestNodeIndex))) { return this._FormControlName_43_5; }
    if (((token === import22.NgControl) && (43 === requestNodeIndex))) { return this._NgControl_43_6; }
    if (((token === import16.NgControlStatus) && (43 === requestNodeIndex))) { return this._NgControlStatus_43_7; }
    if (((token === import15.FormGroupDirective) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._FormGroupDirective_7_3; }
    if (((token === import23.ControlContainer) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._ControlContainer_7_4; }
    if (((token === import16.NgControlStatusGroup) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._NgControlStatusGroup_7_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ErrorComponent_5_4.ngOnInit(); }
    changes = (null as any);
    const currVal_3:any = this.context.signUpForm;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._FormGroupDirective_7_3.form = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['form'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._FormGroupDirective_7_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_13:any = 'firstName';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._FormControlName_11_5.name = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._FormControlName_11_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_23:any = 'lastName';
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._FormControlName_19_5.name = currVal_23;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_23,currVal_23);
      this._expr_23 = currVal_23;
    }
    if ((changes !== (null as any))) { this._FormControlName_19_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_33:any = 'email';
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this._FormControlName_27_5.name = currVal_33;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_33,currVal_33);
      this._expr_33 = currVal_33;
    }
    if ((changes !== (null as any))) { this._FormControlName_27_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_43:any = 'password';
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this._FormControlName_35_5.name = currVal_43;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_43,currVal_43);
      this._expr_43 = currVal_43;
    }
    if ((changes !== (null as any))) { this._FormControlName_35_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_53:any = 'confirmPassword';
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this._FormControlName_43_5.name = currVal_53;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_53,currVal_53);
      this._expr_53 = currVal_53;
    }
    if ((changes !== (null as any))) { this._FormControlName_43_5.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = this._NgControlStatusGroup_7_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_7,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_7_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_7,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_7_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_7,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_7_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_7,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_7_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_7,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_7_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_7,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_12:any = this._el_11.value;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_11,'active',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_14:any = this._NgControlStatus_11_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_11,'ng-untouched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_11_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_11,'ng-touched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_11_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_11,'ng-pristine',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_11_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_11,'ng-dirty',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_11_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_11,'ng-valid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_11_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_11,'ng-invalid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_22:any = this._el_19.value;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_19,'active',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_24:any = this._NgControlStatus_19_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_19,'ng-untouched',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_19_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_19,'ng-touched',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_19_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_19,'ng-pristine',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_19_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_19,'ng-dirty',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_19_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_19,'ng-valid',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_19_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_19,'ng-invalid',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_32:any = this._el_27.value;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_27,'active',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_34:any = this._NgControlStatus_27_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_27,'ng-untouched',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_27_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_27,'ng-touched',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_27_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_27,'ng-pristine',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_27_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_27,'ng-dirty',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_27_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_27,'ng-valid',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgControlStatus_27_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_27,'ng-invalid',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_42:any = this._el_35.value;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_35,'active',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_44:any = this._NgControlStatus_35_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_35,'ng-untouched',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this._NgControlStatus_35_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_35,'ng-touched',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = this._NgControlStatus_35_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_35,'ng-pristine',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_47:any = this._NgControlStatus_35_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementClass(this._el_35,'ng-dirty',currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_48:any = this._NgControlStatus_35_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_35,'ng-valid',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = this._NgControlStatus_35_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementClass(this._el_35,'ng-invalid',currVal_49);
      this._expr_49 = currVal_49;
    }
    const currVal_52:any = this._el_43.value;
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementClass(this._el_43,'active',currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_54:any = this._NgControlStatus_43_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setElementClass(this._el_43,'ng-untouched',currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_55:any = this._NgControlStatus_43_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this.renderer.setElementClass(this._el_43,'ng-touched',currVal_55);
      this._expr_55 = currVal_55;
    }
    const currVal_56:any = this._NgControlStatus_43_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_56,currVal_56)) {
      this.renderer.setElementClass(this._el_43,'ng-pristine',currVal_56);
      this._expr_56 = currVal_56;
    }
    const currVal_57:any = this._NgControlStatus_43_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this.renderer.setElementClass(this._el_43,'ng-dirty',currVal_57);
      this._expr_57 = currVal_57;
    }
    const currVal_58:any = this._NgControlStatus_43_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this.renderer.setElementClass(this._el_43,'ng-valid',currVal_58);
      this._expr_58 = currVal_58;
    }
    const currVal_59:any = this._NgControlStatus_43_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this.renderer.setElementClass(this._el_43,'ng-invalid',currVal_59);
      this._expr_59 = currVal_59;
    }
    const currVal_60:boolean = !this.context.signUpForm.valid;
    if (import4.checkBinding(throwOnChange,this._expr_60,currVal_60)) {
      this.renderer.setElementProperty(this._el_49,'disabled',currVal_60);
      this._expr_60 = currVal_60;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._FormControlName_11_5.ngOnDestroy();
    this._FormControlName_19_5.ngOnDestroy();
    this._FormControlName_27_5.ngOnDestroy();
    this._FormControlName_35_5.ngOnDestroy();
    this._FormControlName_43_5.ngOnDestroy();
  }
  private _handle_ngSubmit_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_7_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_7_3.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_7_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_7_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_11_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_11_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_11_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_19_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_19_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_19_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_27_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_27_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_27_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_27_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_35_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_35_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_35_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_35_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_43_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_43_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_43_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_43_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SignupComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SignupComponent> {
  if ((renderType_SignupComponent === (null as any))) { (renderType_SignupComponent = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_SignupComponent,{})); }
  return new _View_SignupComponent0(viewUtils,parentInjector,declarationEl);
}