/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './editor-two-columns.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '../editor-header/normal/header-normal.component';
import * as import11 from '../editor-nav/two-colums/nav-two-columns.component';
import * as import12 from '../editor-main/two-colums/main-two-columns.component';
import * as import13 from '../editor-footer/normal/footer-normal.component';
import * as import14 from '../editor-header/normal/header-normal.component.ngfactory';
import * as import15 from '../editor-nav/two-colums/nav-two-columns.component.ngfactory';
import * as import16 from '../editor-main/two-colums/main-two-columns.component.ngfactory';
import * as import17 from '../editor-footer/normal/footer-normal.component.ngfactory';
var renderType_EditorTwoColumnsComponent_Host:import0.RenderComponentType = (null as any);
class _View_EditorTwoColumnsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _EditorTwoColumnsComponent_0_4:import3.EditorTwoColumnsComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_EditorTwoColumnsComponent_Host0,renderType_EditorTwoColumnsComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('dip-editor-two-columns',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_EditorTwoColumnsComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._EditorTwoColumnsComponent_0_4 = new import3.EditorTwoColumnsComponent();
    this._appEl_0.initComponent(this._EditorTwoColumnsComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._EditorTwoColumnsComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.EditorTwoColumnsComponent) && (0 === requestNodeIndex))) { return this._EditorTwoColumnsComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._EditorTwoColumnsComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_EditorTwoColumnsComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_EditorTwoColumnsComponent_Host === (null as any))) { (renderType_EditorTwoColumnsComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_EditorTwoColumnsComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const EditorTwoColumnsComponentNgFactory:import9.ComponentFactory<import3.EditorTwoColumnsComponent> = new import9.ComponentFactory<import3.EditorTwoColumnsComponent>('dip-editor-two-columns',viewFactory_EditorTwoColumnsComponent_Host0,import3.EditorTwoColumnsComponent);
const styles_EditorTwoColumnsComponent:any[] = ([] as any[]);
var renderType_EditorTwoColumnsComponent:import0.RenderComponentType = (null as any);
class _View_EditorTwoColumnsComponent0 extends import1.AppView<import3.EditorTwoColumnsComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _HeaderNormalComponent_2_4:import10.HeaderNormalComponent;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _NavTwoColumnsComponent_6_4:import11.NavTwoColumnsComponent;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _MainTwoColumnsComponent_8_4:import12.MainTwoColumnsComponent;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _FooterNormalComponent_11_4:import13.FooterNormalComponent;
  _text_12:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_EditorTwoColumnsComponent0,renderType_EditorTwoColumnsComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','relative clearfix');
    this.renderer.setElementAttribute(this._el_0,'id','editor-app');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'dip-header-normal',(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import14.viewFactory_HeaderNormalComponent0(this.viewUtils,this.injector(2),this._appEl_2);
    this._HeaderNormalComponent_2_4 = new import10.HeaderNormalComponent();
    this._appEl_2.initComponent(this._HeaderNormalComponent_2_4,([] as any[]),compView_2);
    compView_2.create(this._HeaderNormalComponent_2_4,([] as any[]),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','relative');
    this.renderer.setElementAttribute(this._el_4,'style','display: flex;');
    this._text_5 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'dip-nav-two-columns',(null as any));
    this.renderer.setElementAttribute(this._el_6,'style','width: 20%;');
    this._appEl_6 = new import2.AppElement(6,4,this,this._el_6);
    var compView_6:any = import15.viewFactory_NavTwoColumnsComponent0(this.viewUtils,this.injector(6),this._appEl_6);
    this._NavTwoColumnsComponent_6_4 = new import11.NavTwoColumnsComponent();
    this._appEl_6.initComponent(this._NavTwoColumnsComponent_6_4,([] as any[]),compView_6);
    compView_6.create(this._NavTwoColumnsComponent_6_4,([] as any[]),(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_4,'dip-main-two-columns',(null as any));
    this.renderer.setElementAttribute(this._el_8,'style','width: 80%;');
    this._appEl_8 = new import2.AppElement(8,4,this,this._el_8);
    var compView_8:any = import16.viewFactory_MainTwoColumnsComponent0(this.viewUtils,this.injector(8),this._appEl_8);
    this._MainTwoColumnsComponent_8_4 = new import12.MainTwoColumnsComponent();
    this._appEl_8.initComponent(this._MainTwoColumnsComponent_8_4,([] as any[]),compView_8);
    compView_8.create(this._MainTwoColumnsComponent_8_4,([] as any[]),(null as any));
    this._text_9 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_0,'dip-footer-normal',(null as any));
    this._appEl_11 = new import2.AppElement(11,0,this,this._el_11);
    var compView_11:any = import17.viewFactory_FooterNormalComponent0(this.viewUtils,this.injector(11),this._appEl_11);
    this._FooterNormalComponent_11_4 = new import13.FooterNormalComponent();
    this._appEl_11.initComponent(this._FooterNormalComponent_11_4,([] as any[]),compView_11);
    compView_11.create(this._FooterNormalComponent_11_4,([] as any[]),(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.HeaderNormalComponent) && (2 === requestNodeIndex))) { return this._HeaderNormalComponent_2_4; }
    if (((token === import11.NavTwoColumnsComponent) && (6 === requestNodeIndex))) { return this._NavTwoColumnsComponent_6_4; }
    if (((token === import12.MainTwoColumnsComponent) && (8 === requestNodeIndex))) { return this._MainTwoColumnsComponent_8_4; }
    if (((token === import13.FooterNormalComponent) && (11 === requestNodeIndex))) { return this._FooterNormalComponent_11_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.page.header;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._HeaderNormalComponent_2_4.header = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HeaderNormalComponent_2_4.ngOnInit(); }
    const currVal_1:any = this.context.page.nav;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NavTwoColumnsComponent_6_4.nav = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.context.solution.pages;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NavTwoColumnsComponent_6_4.pages = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._NavTwoColumnsComponent_6_4.ngOnInit(); }
    const currVal_3:any = this.context.page.main;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MainTwoColumnsComponent_8_4.main = currVal_3;
      this._expr_3 = currVal_3;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._MainTwoColumnsComponent_8_4.ngOnInit(); }
    const currVal_4:any = this.context.page.footer;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._FooterNormalComponent_11_4.footer = currVal_4;
      this._expr_4 = currVal_4;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._FooterNormalComponent_11_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_EditorTwoColumnsComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.EditorTwoColumnsComponent> {
  if ((renderType_EditorTwoColumnsComponent === (null as any))) { (renderType_EditorTwoColumnsComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_EditorTwoColumnsComponent,{})); }
  return new _View_EditorTwoColumnsComponent0(viewUtils,parentInjector,declarationEl);
}