/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './market.module';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '@angular/common/src/common_module';
import * as import4 from '@angular/forms/src/directives';
import * as import5 from '@angular/forms/src/form_providers';
import * as import6 from 'ng2-uploader/src/module/ng2-uploader.module';
import * as import7 from '../shared/shared.module';
import * as import8 from '@angular/common/src/localization';
import * as import9 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import10 from 'ng2-uploader/src/services/ng2-uploader';
import * as import11 from './market.service';
import * as import12 from '@angular/core/src/di/injector';
import * as import13 from './market.component.ngfactory';
import * as import14 from '@angular/core/src/i18n/tokens';
import * as import15 from './market.component';
import * as import16 from '@angular/http/src/http';
import * as import17 from '@angular/router/src/router_config_loader';
class MarketModuleInjector extends import0.NgModuleInjector<import1.MarketModule> {
  _RouterModule_0:import2.RouterModule;
  _CommonModule_1:import3.CommonModule;
  _InternalFormsSharedModule_2:import4.InternalFormsSharedModule;
  _FormsModule_3:import5.FormsModule;
  _Ng2UploaderModule_4:import6.Ng2UploaderModule;
  _SharedModule_5:import7.SharedModule;
  _MarketModule_6:import1.MarketModule;
  __NgLocalization_7:import8.NgLocaleLocalization;
  __RadioControlRegistry_8:import9.RadioControlRegistry;
  __Ng2Uploader_9:import10.Ng2Uploader;
  __ROUTES_10:any[];
  __MarketService_11:import11.MarketService;
  constructor(parent:import12.Injector) {
    super(parent,[import13.MarketComponentNgFactory],([] as any[]));
  }
  get _NgLocalization_7():import8.NgLocaleLocalization {
    if ((this.__NgLocalization_7 == (null as any))) { (this.__NgLocalization_7 = new import8.NgLocaleLocalization(this.parent.get(import14.LOCALE_ID))); }
    return this.__NgLocalization_7;
  }
  get _RadioControlRegistry_8():import9.RadioControlRegistry {
    if ((this.__RadioControlRegistry_8 == (null as any))) { (this.__RadioControlRegistry_8 = new import9.RadioControlRegistry()); }
    return this.__RadioControlRegistry_8;
  }
  get _Ng2Uploader_9():import10.Ng2Uploader {
    if ((this.__Ng2Uploader_9 == (null as any))) { (this.__Ng2Uploader_9 = new import10.Ng2Uploader()); }
    return this.__Ng2Uploader_9;
  }
  get _ROUTES_10():any[] {
        if ((this.__ROUTES_10 == (null as any))) { (this.__ROUTES_10 = [[{
          path: '',
          component: import15.MarketComponent,
          pathMatch: 'full'
        }
    ]]); }
    return this.__ROUTES_10;
  }
  get _MarketService_11():import11.MarketService {
    if ((this.__MarketService_11 == (null as any))) { (this.__MarketService_11 = new import11.MarketService(this.parent.get(import16.Http))); }
    return this.__MarketService_11;
  }
  createInternal():import1.MarketModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ROUTER_FORROOT_GUARD,(null as any)));
    this._CommonModule_1 = new import3.CommonModule();
    this._InternalFormsSharedModule_2 = new import4.InternalFormsSharedModule();
    this._FormsModule_3 = new import5.FormsModule();
    this._Ng2UploaderModule_4 = new import6.Ng2UploaderModule();
    this._SharedModule_5 = new import7.SharedModule();
    this._MarketModule_6 = new import1.MarketModule();
    return this._MarketModule_6;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import3.CommonModule)) { return this._CommonModule_1; }
    if ((token === import4.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_2; }
    if ((token === import5.FormsModule)) { return this._FormsModule_3; }
    if ((token === import6.Ng2UploaderModule)) { return this._Ng2UploaderModule_4; }
    if ((token === import7.SharedModule)) { return this._SharedModule_5; }
    if ((token === import1.MarketModule)) { return this._MarketModule_6; }
    if ((token === import8.NgLocalization)) { return this._NgLocalization_7; }
    if ((token === import9.RadioControlRegistry)) { return this._RadioControlRegistry_8; }
    if ((token === import10.Ng2Uploader)) { return this._Ng2Uploader_9; }
    if ((token === import17.ROUTES)) { return this._ROUTES_10; }
    if ((token === import11.MarketService)) { return this._MarketService_11; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const MarketModuleNgFactory:import0.NgModuleFactory<import1.MarketModule> = new import0.NgModuleFactory(MarketModuleInjector,import1.MarketModule);