/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './main-theme.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
var renderType_MainThemeComponent_Host:import0.RenderComponentType = (null as any);
class _View_MainThemeComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _MainThemeComponent_0_4:import3.MainThemeComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MainThemeComponent_Host0,renderType_MainThemeComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('dip-main-theme',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MainThemeComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MainThemeComponent_0_4 = new import3.MainThemeComponent();
    this._appEl_0.initComponent(this._MainThemeComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._MainThemeComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.MainThemeComponent) && (0 === requestNodeIndex))) { return this._MainThemeComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._MainThemeComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MainThemeComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_MainThemeComponent_Host === (null as any))) { (renderType_MainThemeComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_MainThemeComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const MainThemeComponentNgFactory:import9.ComponentFactory<import3.MainThemeComponent> = new import9.ComponentFactory<import3.MainThemeComponent>('dip-main-theme',viewFactory_MainThemeComponent_Host0,import3.MainThemeComponent);
const styles_MainThemeComponent:any[] = ([] as any[]);
var renderType_MainThemeComponent:import0.RenderComponentType = (null as any);
class _View_MainThemeComponent0 extends import1.AppView<import3.MainThemeComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MainThemeComponent0,renderType_MainThemeComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','clearfix');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','left');
    this.renderer.setElementAttribute(this._el_2,'style','width: 50%;');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'button',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Theme Grid',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','left');
    this.renderer.setElementAttribute(this._el_8,'style','width: 50%;');
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'button',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Theme Rows',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','left top20');
    this.renderer.setElementAttribute(this._el_14,'style','width: 50%;');
    this._text_15 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'button',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Contact Form',(null as any));
    this._text_18 = this.renderer.createText(this._el_14,'\n    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','left top20');
    this.renderer.setElementAttribute(this._el_20,'style','width: 50%;');
    this._text_21 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_20,'button',(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Scroll',(null as any));
    this._text_25 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._text_26 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_27 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_10,'click',this.eventHandler(this._handle_click_10_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_16,'click',this.eventHandler(this._handle_click_16_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_23,'click',this.eventHandler(this._handle_click_23_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,([] as any[]));
    return (null as any);
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.main.layout = this.context.layoutTypes.Grid)) !== false);
    return (true && pd_0);
  }
  private _handle_click_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.main.layout = this.context.layoutTypes.Rows)) !== false);
    return (true && pd_0);
  }
  private _handle_click_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.main.layout = this.context.layoutTypes.ContactForm)) !== false);
    return (true && pd_0);
  }
  private _handle_click_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.main.layout = this.context.layoutTypes.Scroll)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_MainThemeComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.MainThemeComponent> {
  if ((renderType_MainThemeComponent === (null as any))) { (renderType_MainThemeComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_MainThemeComponent,{})); }
  return new _View_MainThemeComponent0(viewUtils,parentInjector,declarationEl);
}